url: http://theorypc.ca
name: 'Trentent Tye - Microsoft MVP'
description: Adventures in application delivery
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
